version: '2'

services:
  texture-wrapper:
    build:
      context: .
      dockerfile: Dockerfile-dev
    hostname: texture-wrapper
    environment:
      - XML_FILES=/app/texture_wrapper/files
    volumes:
      - .:/app
    stdin_open: True
    tty: True
    ports:
      - "6543:6543"
    command: ['pserve', 'development.ini', '--reload']